version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: hipaa-postgres
    ports:
      - "5433:5432" # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
